# This is a basic workflow to help you get started with Actions

name: Deploy tagged release on tagged push to master

on:
  push:
    branches:
      - master
    tags:
      - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tagged-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        
      - name: Install yarn
        run: npm i -g yarn
        
      - name: Build dist
        run: yarn build
        
      - name: Compile to single-file .js
        run: yarn ncc build dist/index.js -o out
        
      - name: Generate Linux x64 binary executable
        run: yarn nexe out/index.js -o vInc -t linux-x64 --build
        
      - name: Generate Windows x64 binary executable
        run: yarn nexe out/index.js -o vInc -t windows-x64 --build
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: "vInc*"
          

